dataset_path: Phando/nlvr2-llava
dataset_name: default
dataset_kwargs:
  token: True
task: "nlvr2"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.nlvr2_doc_to_visual
doc_to_text: !function utils.nlvr2_doc_to_text
doc_to_target: !function utils.nlvr2_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.nlvr2_process_result
metadata:
  - version: 0.0

model_specific_prompt_kwargs:
  default:
    hypothesis_prompt: "Hypothesis: "   
    nlvr2_image_dir: /data/tir/projects/tir1/corpora/nlvr2-llava/images 
